In [1]:
import numpy as np

In [2]:
# 0에서 10까지의 원소를 갖는 학습 array 생성
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1, 1)

# 2x + 1의 값을 갖는 라벨 array 생성
y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1, 1)

In [3]:
x_train

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]], dtype=float32)

In [4]:
y_train

array([[ 1.],
       [ 3.],
       [ 5.],
       [ 7.],
       [ 9.],
       [11.],
       [13.],
       [15.],
       [17.],
       [19.],
       [21.]], dtype=float32)

In [5]:
import torch

from torch.autograd import Variable

class LinearRegression(torch.nn.Module):
  def __init__(self, inputSize, outputSize):
    super(LinearRegression, self).__init__()
    self.linear = torch.nn.Linear(inputSize, outputSize)

  def forward(self, x):
    out = self.linear(x)
    return out

In [6]:
# 입력 및 출력 차원 정의, 하이퍼 파라미터 정의
inputDim = 1
outputDim = 1
learningRate = 0.01
epochs = 100

model = LinearRegression(inputDim, outputDim)
# cuda 사용이 가능한 경우, cuda 메모리에 로드
if torch.cuda.is_available():
  model.cuda()

In [7]:
# loss function 및 optimizer 정의
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learningRate)

In [8]:
for epoch in range(epochs):
  # input과 label을 PyTorch Variable 객체로 변환
  if torch.cuda.is_available():
    inputs = Variable(torch.from_numpy(x_train).cuda())
    labels = Variable(torch.from_numpy(y_train).cuda())
  else:
    inputs = Variable(torch.from_numpy(x_train))
    labels = Variable(torch.from_numpy(y_train))

  # 이전 기록된 gradient를 0으로 초기화
  optimizer.zero_grad()

  # model을 통해 input forward propagation 진행
  outputs = model(inputs)

  # loss 값 계산
  loss = criterion(outputs, labels)
  print(loss)
  # 모든 파라미터에 대해 gradient 계산
  loss.backward()

  # 파라미터 업데이트
  optimizer.step()

  print('epoch {}, loss {}'.format(epoch, loss.item()))

tensor(74.0193, device='cuda:0', grad_fn=<MseLossBackward0>)
epoch 0, loss 74.019287109375
tensor(6.7210, device='cuda:0', grad_fn=<MseLossBackward0>)
epoch 1, loss 6.721015930175781
tensor(1.2241, device='cuda:0', grad_fn=<MseLossBackward0>)
epoch 2, loss 1.2240792512893677
tensor(0.7682, device='cuda:0', grad_fn=<MseLossBackward0>)
epoch 3, loss 0.768163800239563
tensor(0.7235, device='cuda:0', grad_fn=<MseLossBackward0>)
epoch 4, loss 0.7235128283500671
tensor(0.7125, device='cuda:0', grad_fn=<MseLossBackward0>)
epoch 5, loss 0.7124910950660706
tensor(0.7043, device='cuda:0', grad_fn=<MseLossBackward0>)
epoch 6, loss 0.7042949199676514
tensor(0.6964, device='cuda:0', grad_fn=<MseLossBackward0>)
epoch 7, loss 0.6964106559753418
tensor(0.6886, device='cuda:0', grad_fn=<MseLossBackward0>)
epoch 8, loss 0.6886321902275085
tensor(0.6809, device='cuda:0', grad_fn=<MseLossBackward0>)
epoch 9, loss 0.6809422373771667
tensor(0.6733, device='cuda:0', grad_fn=<MseLossBackward0>)
epoch 10, loss

In [9]:
# 추론 시 gradient를 계산할 필요가 없으므로 gradient 비활성화
with torch.no_grad():
  if torch.cuda.is_available():
    predicted = model(Variable(torch.from_numpy(x_train).cuda())).cpu().data.numpy()
  else:
    predicted = model(Variable(torch.from_numpy(x_train))).data.numpy()
  print(predicted)


[[ 0.07391421]
 [ 2.207279  ]
 [ 4.3406434 ]
 [ 6.474008  ]
 [ 8.607373  ]
 [10.740738  ]
 [12.874103  ]
 [15.007467  ]
 [17.140831  ]
 [19.274197  ]
 [21.40756   ]]


In [10]:
y_train

array([[ 1.],
       [ 3.],
       [ 5.],
       [ 7.],
       [ 9.],
       [11.],
       [13.],
       [15.],
       [17.],
       [19.],
       [21.]], dtype=float32)

In [11]:
# model의 파라미터를 순회하여 name과 parameter 값 출력
for p in model.parameters():
  if p.requires_grad:
    print(p.name, p.data)

None tensor([[2.1334]], device='cuda:0')
None tensor([0.0739], device='cuda:0')
