In [2]:
import torch
import numpy as np

In [5]:
t1 = torch.FloatTensor(np.arange(10).reshape(2,5))

t1

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [7]:
t2 = torch.FloatTensor(np.arange(10).reshape(5,2))

t2

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [8]:
t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])