In [1]:
import numpy as np

n_array = np.arange(10).reshape(2,5)

print(n_array)
print("Ndin :", n_array.ndim, "shape :", n_array.shape )

[[0 1 2 3 4]
 [5 6 7 8 9]]
Ndin : 2 shape : (2, 5)


In [2]:
import torch

t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape :", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape : torch.Size([2, 5])


In [3]:
import sys
print(sys.executable)

c:\Users\user\miniconda3\envs\ml\python.exe


In [4]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.5.1
True


In [ ]:
t_array.device

device(type='cpu')