In [1]:
import numpy as np

In [2]:
test_a = np.array([[1,2,3], [4,5,6]], float)

In [5]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [6]:
test_a-test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [8]:
test_matrix = np.array([[1,2,3], [4,5,6]], float)

scalar = 3

test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [9]:
test_matrix-scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [ ]:
test_matrix*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [11]:
test_matrix/5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [12]:
test_matrix // 0.2

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [14]:
test_matrix**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])