In [1]:
import numpy as np

In [12]:
test_array = np.arange(1,11)

test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
test_array = np.arange(1,13).reshape(3,4)

test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [13]:
test_array.mean(), test_array.mean(axis=0)

(np.float64(5.5), np.float64(5.5))

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])

np.hstack((a,b))


array([[1, 2],
       [2, 3],
       [3, 4]])

In [18]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])

np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])

np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])