In [2]:
import numpy as np

In [ ]:
test_array = np.array([1,4,5,8], float)

test_array

numpy.float64

In [6]:
type(test_array[3])

numpy.float64

In [7]:
a = np.array([[1,2,3], [4.5,5,6,]], int)

print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
print(a[0,0])

1


In [9]:
print(a[0][0])

1


In [10]:
a[0,0]= 12
print(a)

[[12  2  3]
 [ 4  5  6]]


In [11]:
a[0][0] = 5
print(a)

[[5 2 3]
 [4 5 6]]


In [14]:
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])

b[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [15]:
b[1,1:3]

array([7, 8])

In [16]:
b[1:3]

array([[ 6,  7,  8,  9, 10]])